package MCalculadora;


/**
* MCalculadora/_ICalculadoraStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* lunes 20 de marzo de 2023 20H36' CET
*/

public class _ICalculadoraStub extends org.omg.CORBA.portable.ObjectImpl implements MCalculadora.ICalculadora
{

  public int sumar (MCalculadora.Operadores Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sumar", true);
                MCalculadora.OperadoresHelper.write ($out, Ops);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return sumar (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // sumar

  public int restar (MCalculadora.Operadores Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("restar", true);
                MCalculadora.OperadoresHelper.write ($out, Ops);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return restar (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // restar

  public int multiplicar (MCalculadora.Operadores Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("multiplicar", true);
                MCalculadora.OperadoresHelper.write ($out, Ops);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return multiplicar (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // multiplicar

  public int dividir (MCalculadora.Operadores Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("dividir", true);
                MCalculadora.OperadoresHelper.write ($out, Ops);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return dividir (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // dividir

  public double exponencial (MCalculadora.Operadores Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("exponencial", true);
                MCalculadora.OperadoresHelper.write ($out, Ops);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return exponencial (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // exponencial

  public double raiz (MCalculadora.Operadores Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("raiz", true);
                MCalculadora.OperadoresHelper.write ($out, Ops);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return raiz (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // raiz

  public double modulo (MCalculadora.Operadores Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("modulo", true);
                MCalculadora.OperadoresHelper.write ($out, Ops);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return modulo (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // modulo

  public double factorial (MCalculadora.Operadores Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("factorial", true);
                MCalculadora.OperadoresHelper.write ($out, Ops);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return factorial (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // factorial

  public double potencia (MCalculadora.Operadores Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("potencia", true);
                MCalculadora.OperadoresHelper.write ($out, Ops);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return potencia (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // potencia

  public double logaritmo (MCalculadora.Operadores Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("logaritmo", true);
                MCalculadora.OperadoresHelper.write ($out, Ops);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return logaritmo (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // logaritmo

  public double logaritmoBase10 (MCalculadora.Operadores Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("logaritmoBase10", true);
                MCalculadora.OperadoresHelper.write ($out, Ops);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return logaritmoBase10 (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // logaritmoBase10

  public double seno (MCalculadora.Operadores Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("seno", true);
                MCalculadora.OperadoresHelper.write ($out, Ops);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return seno (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // seno

  public double coseno (MCalculadora.Operadores Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("coseno", true);
                MCalculadora.OperadoresHelper.write ($out, Ops);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return coseno (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // coseno

  public double tangente (MCalculadora.Operadores Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("tangente", true);
                MCalculadora.OperadoresHelper.write ($out, Ops);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return tangente (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // tangente

  public double secante (MCalculadora.Operadores Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("secante", true);
                MCalculadora.OperadoresHelper.write ($out, Ops);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return secante (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // secante

  public double cosecante (MCalculadora.Operadores Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cosecante", true);
                MCalculadora.OperadoresHelper.write ($out, Ops);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return cosecante (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // cosecante

  public double cotangente (MCalculadora.Operadores Ops)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cotangente", true);
                MCalculadora.OperadoresHelper.write ($out, Ops);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return cotangente (Ops        );
            } finally {
                _releaseReply ($in);
            }
  } // cotangente

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MCalculadora/ICalculadora:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ICalculadoraStub
