package MCalculadora;


/**
* MCalculadora/ICalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* lunes 20 de marzo de 2023 20H36' CET
*/

public interface ICalculadoraOperations 
{
  int sumar (MCalculadora.Operadores Ops);
  int restar (MCalculadora.Operadores Ops);
  int multiplicar (MCalculadora.Operadores Ops);
  int dividir (MCalculadora.Operadores Ops);
  double exponencial (MCalculadora.Operadores Ops);
  double raiz (MCalculadora.Operadores Ops);
  double modulo (MCalculadora.Operadores Ops);
  double factorial (MCalculadora.Operadores Ops);
  double potencia (MCalculadora.Operadores Ops);
  double logaritmo (MCalculadora.Operadores Ops);
  double logaritmoBase10 (MCalculadora.Operadores Ops);
  double seno (MCalculadora.Operadores Ops);
  double coseno (MCalculadora.Operadores Ops);
  double tangente (MCalculadora.Operadores Ops);
  double secante (MCalculadora.Operadores Ops);
  double cosecante (MCalculadora.Operadores Ops);
  double cotangente (MCalculadora.Operadores Ops);
} // interface ICalculadoraOperations
